language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/app-management-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  mvn clean deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: zdr5CYfCzCyqUHIhcwmznaEK4hFPmzKnAsQVSO9Z2LtIZHajc7It+Te0lhUfmNaNnspBbfnOyIPNpjqo43n6bN+f2N7NM1TtuIFIv8fMd9FuNJGgq7MtfuUDcZ9JuqsC1wMl2QxR+AICQYaaD7TMrDnc85l7BN0SCyiy8XT2TSatByHwVyAR50zCgvbXjalY04UtXQYYeiJ/O83N3EyeONmSDHdyBpYtYmoFmVEyCGb8SOS/gFyXmE2labtjHv3Aq+1ZPR/YVky/yjkSAxsvFYOu0eDZZHGXuekL3n+gmN5UvTShjay6iL9R/ncz2CJW5aYppwqgiXs0QOUPaLcErHOwN9YF6NzFTWFylb8KaX1NYHfYmTOs66arfcfli+Oi+zTdCXEqJCyEUepIsaVAhqEXzWlls7jy7O39roJxDtlJS+Ns3B5FleRMIKNiAy38+dOkdy4ui4kFFBfafx7Z22m+D0T3w2Fw2+svBKCJO8Mt3p3zT4fPi0S1YLQvRx9Vfgm+WWUDq9pTlxOhklNgGCU4ZrcqGUCEb+HV7d54LkN3Cx2C+apyBagyfR26Zu/kXaHObNBDoAJBIooHy8NT7wK0ppxB/CFgMJjgw0F6WIE3/jTiO+p93DuCf4pBTzuLqDkj++4gfShBJHLpGbQj23DUe8yBRvT32eSt7F/z2T4=
  - secure: cE0+GSDRbF/UQt7/XwvQTqvLTnzkYDhbUobxdV7ehAd1QEl4B2YVfZ5KVXPFQZrjlnrPPmyw2JEoCO1d4DkI1n1fPLOz0DGhCbikaw8l05d1HUZpMAnAeBeupYlzpPfTPCmL+7hpbQlLk67o9jlTmV+TWzpbwCt1Dt49wFrsnKrVfIkZZ28a94yXBe7fz0e1nwCDYavp/O/OLEuEwOGuaznf5najx5o078xJmQs+VqdofsyCqlwrF7QETSr8i7bMB2YgRNvUJSiSQ4t2ItaPCeaW/nNNFDoPcKE8w+2wfGWiDAdV+1sL/Fd4bPLZ/GhN7fTS3a0yoQ43wB+E9pVht597//Q0xpvWg3EeYYaA6mcSBR7RTBlhgdo5e/3blurvpghdG5wY3II1zk0K8+Jz7t345MUI4B6tnoJopSJ/GiA3AdwBEmqkU5tkIrNQ7bc/wsZLaVAmbgVBGx+exWVKVYSnTh55AdYKBx/Q/Ts/4/BgoJ015JqLxg21kiKsjMbo7sc5Wgz+6uSIWg58EDbZx4Xeg+BvS8NGtDzqkX+O4I90kGbpO0P8uALqM3LlO6g9n1i6o1oeZaGJYhfvxsMo2O/P6+/OWrganpOgZ8MEapjBbPIWXuy3xCkJUzaxNMTCnv3dfz9xoKhJNpn6iSd9VBzWNgiHojK19gXXF9Br5m0=
notifications:
  slack:
    rooms:
      secure: LYH5sMWmvmzZom+rD7OP47CGfoXHNAq9fk+zSfyLIs6n/ZrENkrnuBp3rZTkw9/AC28s5msZ7CFC5iaflhhNcAxEpaSzGINQ5tPv1ZtC4jka7+chy8ZMuwmZrJ00bewFfoStSAYyHaLBTnQvfZJzi8jhLVOx/cs9P+v5Sc1Hi3E91g7SslU7gMI+eNDPo30/I1UyJmwsFlB1pPKz5roNQNGtBu9B7S6Tt5y9yFoM6IreEal9eGGA+iGExMOW1T09N0OKhp3IKP/JgCLQK77/s9AxG40bSh0X+ST+0ABNUjEd+M3deYKlfw9xuvQZcGRhF3kHDnD3EfnhbQfUbWlgiSqT29qH+J0eyLi5BT+F52gMhnHRZaUjvnkdpMlUmX4BFV2yHoonE34EbGcTirNpiPwKmkcza7u00K9oW132C7dip7dH2N+exp2IwlnXJiQ0e+xKdp+fNpcvkSbtdM42rn39C0Z1oLA2vj0CzkxtVofki555XoJehFGOusd8jnZ9VH9vi7OXP9AV8LeRsX1J7yfbUcKipAjF1JlsuKFP1spA4KLoyWdM0yuGJQlAV8lPGJJ3UPdVnG3ctyUsofow+PF8KU1p5sSPwXTUU9lnaf8soIR7Rwejwe/TNOeeGoZHyMGPiIKk3jtcJY9uYWXBsHiPaeYVTRxjcypiohyutSo=
    on_success: change
    on_failure: always
