language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- npm run deploy
env:
  global:
    secure: mG1dzEFSnVQqeTNErk8YphX/yrLCamM/knbsbZZh/9Y1NHu0yYQTwp0xDkL/rsOJfZ/6ukm2D+UjCra1+e0otFDTnEVh9C3jLoBYFcDhgs5SZSbSrX4wOOeDDsE+smKRCw3j1AVeJimNrDv+SHibCWbEeJu+8tD3KPc+PS6vsvvjC1QOa0QeOnp7MkmYUYzXQFp9QNjanybBgftbjlWbwIvUIwluokUHUYgdFVz23KJEbo6g2kh6tnuPDJw54j/AGBjhmrJyXr8lNwEkqDm1r+cQ2Y4hE+PFvrNlHwONxJpTt/WosfYReqPN89RzGdEXriRwqC9r1Eu9Mgslihk6Db1Wzk6idjEz34EMWt+AZcK5pCgRSURvv4q3JHVz+zBXySOlZG6VOSqu9WUF+LuKtPx5ZZV5eh8/EWp5vHAzOoPY59jgzl4Ln1CYrL+Ku0Ng920jDz3zp6kWp1xi64cwsrhBIAkhUwA4DV5ToYm+V5kKDT5ZuleKWuY27gDamgFFfYt+AVM5rmdqCleIvK5jIMbVTIHbslDSWksY+Fd6J7OWRBaZTc/+d+15ycqtqv8EzWlj8OUd6uZDcevPs1RtLCopDTg8Gu+iuxAkXPIJIB+LQu0HrB84+XPF/YzOIMJKKfww095/I72YVFPTOs6mYdvwenjqSG4hj75Or1aovd0=
notifications:
  slack:
    rooms:
      secure: LYH5sMWmvmzZom+rD7OP47CGfoXHNAq9fk+zSfyLIs6n/ZrENkrnuBp3rZTkw9/AC28s5msZ7CFC5iaflhhNcAxEpaSzGINQ5tPv1ZtC4jka7+chy8ZMuwmZrJ00bewFfoStSAYyHaLBTnQvfZJzi8jhLVOx/cs9P+v5Sc1Hi3E91g7SslU7gMI+eNDPo30/I1UyJmwsFlB1pPKz5roNQNGtBu9B7S6Tt5y9yFoM6IreEal9eGGA+iGExMOW1T09N0OKhp3IKP/JgCLQK77/s9AxG40bSh0X+ST+0ABNUjEd+M3deYKlfw9xuvQZcGRhF3kHDnD3EfnhbQfUbWlgiSqT29qH+J0eyLi5BT+F52gMhnHRZaUjvnkdpMlUmX4BFV2yHoonE34EbGcTirNpiPwKmkcza7u00K9oW132C7dip7dH2N+exp2IwlnXJiQ0e+xKdp+fNpcvkSbtdM42rn39C0Z1oLA2vj0CzkxtVofki555XoJehFGOusd8jnZ9VH9vi7OXP9AV8LeRsX1J7yfbUcKipAjF1JlsuKFP1spA4KLoyWdM0yuGJQlAV8lPGJJ3UPdVnG3ctyUsofow+PF8KU1p5sSPwXTUU9lnaf8soIR7Rwejwe/TNOeeGoZHyMGPiIKk3jtcJY9uYWXBsHiPaeYVTRxjcypiohyutSo=
    on_success: change
    on_failure: always
