export const coreApps = [
    { name: 'App Management', shortName: 'app-management' },
    { name: 'Cache Cleaner', shortName: 'cache-cleaner' },
    { name: 'Capture', shortName: 'capture' },
    { name: 'Dashboard', shortName: 'dashboard' },
    { name: 'Data Administration', shortName: 'data-administration' },
    { name: 'Data Approval', shortName: 'approval' },
    { name: 'Data Entry', shortName: 'dataentry' },
    { name: 'Data Quality', shortName: 'data-quality' },
    { name: 'Data Visualizer', shortName: 'data-visualizer' },
    { name: 'Datastore', shortName: 'datastore' },
    { name: 'Event Reports', shortName: 'event-reports' },
    { name: 'Event Visualizer', shortName: 'event-visualizer' },
    { name: 'Import/Export', shortName: 'import-export' },
    { name: 'Interpretations', shortName: 'interpretation' },
    { name: 'Maintenance', shortName: 'maintenance' },
    { name: 'Maps', shortName: 'maps' },
    { name: 'Menu Management', shortName: 'menu-management' },
    { name: 'Messaging', shortName: 'messaging' },
    { name: 'Pivot Table', shortName: 'pivot' },
    { name: 'Reports', shortName: 'reports' },
    { name: 'SMS Configuration', shortName: 'sms-configuration' },
    { name: 'Scheduler', shortName: 'scheduler' },
    { name: 'System Settings', shortName: 'settings' },
    { name: 'Tracker Capture', shortName: 'tracker-capture' },
    { name: 'Translations', shortName: 'translations' },
    { name: 'Usage Analytics', shortName: 'usage-analytics' },
    { name: 'User Profile', shortName: 'user-profile' },
    { name: 'Users', shortName: 'user' },
]
